[package]
name = "topdown-shooter-bevy-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = "0.8.1"
# tungstenite = {version = "0.17.3", features = ["native-tls-vendored"]}
url = "2.3.1"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.86"
serde = {version = "1.0.145", features = ["derive"]} 
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = {version = "0.3.60", features = ["console"]}
wascap = "0.8.0"
base64 = "0.13.0"
console_error_panic_hook = "0.1.7"
ws_stream_wasm = "0.7.3"
pharos = "0.5.3"
futures = "0.3.24"
wasm-logger = "0.2.0"
log = "0.4.17"
futures-lite = "1.12.0"
noop-waker = "0.1.0"
