[package]
name = "topdown-shooter-bevy-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = "0.8.1"
# tungstenite = {version = "0.17.3", features = ["native-tls"]}
url = "2.3.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0.86"
serde = "1.0.145"
jsonwebtoken = "8.1.1"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = {version = "0.3.60", features = ["console"]}
console_error_panic_hook = "0.1.7"
